export const NOTEBOOKLM_SUPPORTED_LANGUAGES: Record<string, string> = {
  en: 'English',
  zh_Hans: '中文（简体）',
  zh_Hant: '中文（繁體）',
  es: 'Español',
  es_419: 'Español (Latinoamérica)',
  es_MX: 'Español (México)',
  hi: 'हिन्दी',
  ar_001: 'العربية',
  ar_eg: 'العربية (مصر)',
  pt_BR: 'Português (Brasil)',
  pt_PT: 'Português (Portugal)',
  bn: 'বাংলা',
  ru: 'Русский',
  ja: '日本語',
  pa: 'ਪੰਜਾਬੀ',
  de: 'Deutsch',
  jv: 'Basa Jawa',
  ko: '한국어',
  fr: 'Français',
  fr_CA: 'Français (Canada)',
  te: 'తెలుగు',
  vi: 'Tiếng Việt',
  mr: 'मराठी',
  ta: 'தமிழ்',
  tr: 'Türkçe',
  ur: 'اردو',
  it: 'Italiano',
  th: 'ไทย',
  gu: 'ગુજરાતી',
  fa: 'فارسی',
  pl: 'Polski',
  uk: 'Українська',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ',
  or: 'ଓଡ଼ିଆ',
  my: 'မြန်မာဘာသာ',
  sw: 'Kiswahili',
  nl_NL: 'Nederlands',
  ro: 'Română',
  hu: 'Magyar',
  el: 'Ελληνικά',
  cs: 'Čeština',
  sv: 'Svenska',
  be: 'Беларуская',
  bg: 'Български',
  hr: 'Hrvatski',
  sk: 'Slovenčina',
  da: 'Dansk',
  fi: 'Suomi',
  nb_NO: 'Norsk Bokmål',
  nn_NO: 'Norsk Nynorsk',
  he: 'עברית',
  iw: 'עברית',
  id: 'Bahasa Indonesia',
  ms: 'Bahasa Melayu',
  fil: 'Filipino',
  ceb: 'Cebuano',
  sr: 'Српски',
  sl: 'Slovenščina',
  sq: 'Shqip',
  mk: 'Македонски',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  hy: 'Հայերեն',
  ka: 'ქართული',
  az: 'Azərbaycanca',
  af: 'Afrikaans',
  am: 'አማርኛ',
  eu: 'Euskara',
  ca: 'Català',
  gl: 'Galego',
  is: 'Íslenska',
  la: 'Latina',
  ne: 'नेपाली',
  ps: 'پښتو',
  sd: 'سنڌي',
  si: 'සිංහල',
  ht: 'Kreyòl Ayisyen',
  kok: 'कोंकणी',
  mai: 'मैथिली',
};
